name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - '*.md'
      - '*.adoc'
      - '*.txt'
      - '.all-contributorsrc'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - '*.md'
      - '*.adoc'
      - '*.txt'
      - '.all-contributorsrc'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y-%m")"
        shell: bash
      - name: Cache Maven Repository
        id: cache-maven
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          # refresh cache every month to avoid unlimited growth
          key: maven-repo-${{ runner.os }}-${{ steps.get-date.outputs.date }}

      - name: Build with Maven
        run: mvn -B formatter:validate install --file pom.xml

      - name: Kubernetes KinD Cluster
        uses: container-tools/kind-action@v2
        with:
          version: v0.17.0
          registry: true
      - name: Install Cert-Manager
        run: |
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.12.2/cert-manager.yaml
      - name: Verify Test
        run: |
          K8S_NAMESPACE=test
          KIND_REGISTRY_GROUP=local
          VERSION=latest
          kubectl create namespace $K8S_NAMESPACE
          kubectl config set-context --current --namespace=$K8S_NAMESPACE
          cd integration-tests/kubernetes-certmanager-ssl
          mvn clean package -Dquarkus.container-image.build=true \
            -Dquarkus.container-image.push=true \
            -Dquarkus.container-image.registry=$KIND_REGISTRY \
            -Dquarkus.container-image.group=$KIND_REGISTRY_GROUP \
            -Dquarkus.container-image.tag=$VERSION \
            -Dquarkus.container-image.insecure=true
          kubectl apply -f target/kubernetes/kubernetes.yml
          # TODO: Investigate why this is failing in CI (it works fine locally)
          # kubectl wait --timeout=120s --for=condition=ready pod -l app.kubernetes.io/name=quarkus-hello-world
          # mvn clean install -Drun-endpoint-test-in-kubernetes=true

      - name: (Only if it failed) Log at failures
        if: failure()
        run: |
          echo "Print secrets:"
          kubectl get secrets -n test
          echo "Get events:"
          kubectl get events -n test
          echo "Deployment resource:"
          kubectl get deployment quarkus-hello-world -n test -o yaml
          echo "Logs of the deployment:"
          kubectl logs deploy/quarkus-hello-world --all-containers=true -n test
          POD_NAME=$(kubectl get pod -l app.kubernetes.io/name=quarkus-hello-world -o name -n test)
          echo "Describe pod:"
          kubectl describe $POD_NAME -n test
          echo "Logs of running pod:"
          kubectl logs $POD_NAME -n test
          echo "Logs of terminated pod:"
          kubectl logs -p $POD_NAME -n test
          echo "Logs of the Cert-Manager certificate:"
          kubectl get Certificate quarkus-hello-world -n test -o yaml

      - name: Delete Project
        run: kubectl delete namespace test
